### ISSUE TITLE
Inference meta-llama2 70b with FSDP

### ISSUE THREAD

**Issue by kiucho** [meta-llama/llama-recipes#255]
Can I inference meta-llama2 70b with FSDP in next condition?
single node/ multi gpus: 4 * A6000(48GB)

**Comment by kiucho** [comment]
Seems like inferencing without FSDP works in 4 * A6000(48GB)
(below command)
```python
export CUDA_VISIBLE_DEVICES=0,1,2,3

python inference.py --model_name meta-llama/Llama-2-70b-hf --prompt_file samsum_prompt.txt   --top_p 0.9 --temperature 1.0 --use_fast_kernels
```
But inference speed is very slow although I use `use_fas_kernels`.
Q1: Is there more way to speed up inference?
Q2: Can I use bf16 during inference with below code?
```python
model.to(torch.bfloat16)
```

**Comment by HamidShojanazeri** [comment]
@kiucho FSDP is not designed for inference path so that would be slower+ need a workaround to enable it. 

> Q1: Is there more way to speed up inference? 

You might want to try using torch.compile() with "reduce_overhead"/ cuda graphs to see if that would run seamlessly for you. We are working on a recipe to do more of optimization to make it faster.

> Q2: Can I use bf16 during inference with below code?

Yes, you can, it should work.

Please let me know how you experiment goes with adding compile/cuda graph there.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
