### ISSUE TITLE
FSDP pure_bf16+anyprecision 

### ISSUE THREAD

**Issue by mathmax12** [meta-llama/llama-recipes#656]
### 🚀 The feature, motivation and pitch

I am trying to use bf16 for training to save the footprint size. Here is the command, which add "--fsdp_config.pure_bf16 True   --fsdp_config.optimizer anyprecision " to make their bf16 use case. But I found there is no change regarding to the memory usage when comparing training with FP32.
torchrun  --nnodes 2 --nproc_per_node 8     --rdzv_id 2212 --rdzv_backend c10d --rdzv_endpoint 10.158.215.85:29500     ./recipes/quickstart/finetuning/finetuning.py  --model_name ./Meta-Llama-3.1-models/Meta-Llama-3.1-8B  --enable_fsdp      --num_epochs 3 --batch_size_training 16 --batching_strategy packing     --dataset alpaca_dataset     --save_model False     --context_length 4096     --fsdp_config.pure_bf16 True   --fsdp_config.optimizer anyprecision 
 
Could someone let me know if I missed anything?
Thanks

**Comment by mreso** [comment]
Hi @mathmax12 
thanks for reporting this observation.
The reason you're seeing no or only a slight difference (depending on when you look at the allocated memory) is that we're not actually loading the model in float32 in any case. This is kind of a bug and kind of not to be honest.

The culprit is [this line](https://github.com/meta-llama/llama-recipes/blob/3e39ed05bdd6426bd0c41253d1b18e478e2cb670/src/llama_recipes/finetuning.py#L127) where we set the torch_dtype to bf16 if we do not set train_config.use_fp16. But at least for llama this is okay because the [default dtype is bf16](https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/blob/main/config.json#L34).

So the only difference I am seeing (just checked on rank 0) is that with pure_bf16 vs mixed precision the max reserved memory after processing a batch with a single sample is about 13% smaller but the actual allocated memory after finishing processing is the same.

I might create a PR to use "auto" instead of bf16 but it would have no change in you example. 

Hope that helps.
