### ISSUE TITLE
Expedited Access Request Llama2 (HF)

### ISSUE THREAD

**Issue by farris** [meta-llama/llama-recipes#765]
### System Info

-

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Would be great to get expedited access to the Llama2 model family, my request has been sitting for a few hours now
https://huggingface.co/meta-llama/Llama-2-7b-hf

### Error logs

-

### Expected behavior

-

**Comment by IgorKasianenko** [comment]
Thank you for your interest in the Llama2 model family and for reaching out. We appreciate your enthusiasm and your request for expedited access.
However, it seems that this issue is not aligned with our [Contributing Guidelines](https://github.com/meta-llama/llama-recipes/blob/main/CONTRIBUTING.md#contributing-to-llama-recipes). Specifically, issues should be used to track public bugs or feature requests that are directly related to the llama-recipes project.
For access requests or other inquiries not related to contributing code or documentation, please refer to https://www.llama.com/llama-downloads/
I would encourage to explore newer more capable models at https://huggingface.co/meta-llama specifically Llama3.2-3B-Instruct, [Llama-3.1-8B-Instruct](https://huggingface.co/datasets/meta-llama/Llama-3.1-8B-Instruct-evals) and [Llama-3.2-11B-Vision-Instruct](https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct)
